# Generated by Django 2.0.13 on 2019-05-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='img')),
                ('stars', models.IntegerField()),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pubs.Pub')),
            ],
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pubs.Pub'),
        ),
    ]
